on:
  push:
    paths:
      - "DC-*"
      - "xml/*"

  pull_request:
    paths:
      - "DC-*"
      - "xml/*"

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: openSUSE/doc-ci@gha-validate
        with:
          dc-files: "DC-release-notes"
          validate-ids: true
          validate-images: true
          validate-tables: true
